export type ZibRoleGroup =
  | 'Command'
  | 'Intelligence'
  | 'Field'
  | 'Creative'
  | 'Systems'
  | 'Oversight'

export type ZibPlaceholder = {
  id: string
  group: ZibRoleGroup
  name: string
  role: string
  note: string
  primary: string
  secondary: string
  tertiary: string
  imageSrc: string | null
}

export const ZIB_ROLE_ORDER: ZibRoleGroup[] = [
  'Command',
  'Intelligence',
  'Field',
  'Creative',
  'Systems',
  'Oversight',
]

export const SCAVENJER_ROLE_DESCRIPTIONS: Record<ZibRoleGroup, string> = {
  Command: 'Scavenjer Xylos for executive prioritization, approvals, and mission control.',
  Intelligence: 'Scavenjer Xylos for source truth, player behavior, doctrine, lore, and operational signal.',
  Field: 'Scavenjer Xylos for AR drops, hosts, business assets, city events, and live readiness.',
  Creative: 'Scavenjer Xylos for Broadcast, Studios, Chronicles, recaps, and reward creative.',
  Systems: 'Scavenjer Xylos for Supabase, Thirdweb, Stripe, Crossmint, Discord, Marbleverse, and site reliability.',
  Oversight: 'Scavenjer Xylos for financial drag, failed jobs, compliance, stale work, and human escalation.',
}

export const BUSINESS_ROLE_DESCRIPTIONS: Record<ZibRoleGroup, string> = {
  Command: 'Business ZiBz for owner-level decisions, weekly priorities, and executive follow-through.',
  Intelligence: 'Business ZiBz for client memory, market signal, relationship context, and reusable knowledge.',
  Field: 'Business ZiBz for delivery, client operations, follow-ups, and daily execution.',
  Creative: 'Business ZiBz for sales assets, proposals, publishing, and presentation quality.',
  Systems: 'Business ZiBz for inboxes, finance, tooling, automations, and operational reliability.',
  Oversight: 'Business ZiBz for cash risk, missed promises, stale relationships, and review gates.',
}

export const ZIB_ROLE_DESCRIPTIONS = SCAVENJER_ROLE_DESCRIPTIONS

export const SCAVENJER_XYLOS_PROFILES: ZibPlaceholder[] = [
  {
    id: 'xylos-scavenjer-gm',
    group: 'Command',
    name: 'Scavenjer GM',
    role: 'Autonomous General Manager',
    note: 'Ranks drops, city events, host approvals, partner work, and creator output into one owner decision queue.',
    imageSrc: null,
    primary: '#67f4ff',
    secondary: '#9bf8ff',
    tertiary: '#dd6fff',
  },
  {
    id: 'xylos-approval-controller',
    group: 'Command',
    name: 'Approval Controller',
    role: 'Human Decision Gate',
    note: 'Prepares approve/hold/escalate packets for reward budgets, launch windows, partner commitments, and live drop risk.',
    imageSrc: null,
    primary: '#dd6fff',
    secondary: '#67f4ff',
    tertiary: '#ffc86f',
  },
  {
    id: 'xylos-player-intel',
    group: 'Intelligence',
    name: 'Player Intelligence',
    role: 'Demand And Behavior Analyst',
    note: 'Reads registrations, city votes, leaderboard movement, Scavenjer Types, Eko ownership, and player readiness signals.',
    imageSrc: null,
    primary: '#8bff8a',
    secondary: '#67f4ff',
    tertiary: '#d8ff9a',
  },
  {
    id: 'xylos-lore-doctrine',
    group: 'Intelligence',
    name: 'Lore And Doctrine',
    role: 'Source Truth Keeper',
    note: 'Keeps Scavenjer doctrine, Eko utility, Marbleverse rules, Chronicles, and simulation canon consistent before publishing.',
    imageSrc: null,
    primary: '#67f4ff',
    secondary: '#dd6fff',
    tertiary: '#8bff8a',
  },
  {
    id: 'xylos-dropops',
    group: 'Field',
    name: 'DropOps',
    role: 'AR Drop Operator',
    note: 'Moves drop requests through asset selection, registration thresholds, time-slot voting, scheduling, Discord alerts, and live execution.',
    imageSrc: null,
    primary: '#ffc86f',
    secondary: '#ff9e75',
    tertiary: '#67f4ff',
  },
  {
    id: 'xylos-host-field',
    group: 'Field',
    name: 'Host And Field Ops',
    role: 'Host Readiness Lead',
    note: 'Qualifies hosts, regions, business assets, real-world rewards, venue readiness, and post-drop evidence.',
    imageSrc: null,
    primary: '#67f4ff',
    secondary: '#ffc86f',
    tertiary: '#ff7c8d',
  },
  {
    id: 'xylos-studio-broadcast',
    group: 'Creative',
    name: 'Broadcast Studio',
    role: 'Content Pipeline Lead',
    note: 'Turns drops, rewards, hosts, city votes, and winner proof into Broadcast, Studios, social, and recap assets.',
    imageSrc: null,
    primary: '#dd6fff',
    secondary: '#ff92da',
    tertiary: '#67f4ff',
  },
  {
    id: 'xylos-business-rewards',
    group: 'Creative',
    name: 'Business Rewards',
    role: 'Partner Value Architect',
    note: 'Shapes business partner offers into real-world rewards, sponsor deliverables, creator angles, and conversion evidence.',
    imageSrc: null,
    primary: '#ff92da',
    secondary: '#67f4ff',
    tertiary: '#ffc86f',
  },
  {
    id: 'xylos-commerce-mint',
    group: 'Systems',
    name: 'Commerce And Mint',
    role: 'Shop And NFT Reliability',
    note: 'Monitors support shop products, Stripe checkout, Crossmint collections, tracked collections, mint jobs, wallets, and failed retries.',
    imageSrc: null,
    primary: '#67f4ff',
    secondary: '#9ab6ff',
    tertiary: '#8bff8a',
  },
  {
    id: 'xylos-integration-reliability',
    group: 'Systems',
    name: 'Integration Reliability',
    role: 'Connector Health Operator',
    note: 'Keeps Supabase, Thirdweb, Discord webhooks, Marbleverse Connect, NeoMarket, Simulations, IPFS, and deployment health visible.',
    imageSrc: null,
    primary: '#9ab6ff',
    secondary: '#67f4ff',
    tertiary: '#8bff8a',
  },
  {
    id: 'xylos-audit-finance',
    group: 'Oversight',
    name: 'Audit And Finance',
    role: 'Risk And Margin Watch',
    note: 'Flags stale work, failed mints, reward overrun, support burden, compliance gaps, and decisions that need the owner.',
    imageSrc: null,
    primary: '#ff7c8d',
    secondary: '#ffc86f',
    tertiary: '#67f4ff',
  },
  {
    id: 'xylos-member-support',
    group: 'Oversight',
    name: 'Member Support',
    role: 'Player And Partner Escalation',
    note: 'Routes wallet, Eko, profile, Marbleverse ID, drop registration, and business partner issues to the right next action.',
    imageSrc: null,
    primary: '#ffc86f',
    secondary: '#ff7c8d',
    tertiary: '#67f4ff',
  },
]

export const BUSINESS_ZIB_PROFILES: ZibPlaceholder[] = [
  {
    id: 'zib-executive-operator',
    group: 'Command',
    name: 'Executive Operator',
    role: 'Owner Priorities',
    note: 'Turns scattered business work into a weekly owner queue with clear decisions, follow-ups, and outcomes.',
    imageSrc: null,
    primary: '#2fc7c9',
    secondary: '#6fdadd',
    tertiary: '#d85f9d',
  },
  {
    id: 'zib-revenue-chief',
    group: 'Command',
    name: 'Revenue Chief',
    role: 'Pipeline And Offers',
    note: 'Keeps proposals, retainers, partnerships, referrals, and renewals moving without losing commercial context.',
    imageSrc: null,
    primary: '#d85f9d',
    secondary: '#2fc7c9',
    tertiary: '#d39a38',
  },
  {
    id: 'zib-client-memory',
    group: 'Intelligence',
    name: 'Client Memory',
    role: 'Relationship Context',
    note: 'Maintains client notes, last touches, buying context, proposal history, and personal relationship cues.',
    imageSrc: null,
    primary: '#67b26f',
    secondary: '#2fc7c9',
    tertiary: '#a6bd54',
  },
  {
    id: 'zib-market-signal',
    group: 'Intelligence',
    name: 'Market Signal',
    role: 'Opportunity Analyst',
    note: 'Surfaces which offers, accounts, audiences, and partner conversations deserve owner attention next.',
    imageSrc: null,
    primary: '#2fc7c9',
    secondary: '#d85f9d',
    tertiary: '#67b26f',
  },
  {
    id: 'zib-delivery-ops',
    group: 'Field',
    name: 'Delivery Ops',
    role: 'Client Promise Keeper',
    note: 'Tracks active work, blockers, handoffs, due dates, and client commitments until delivery is closed.',
    imageSrc: null,
    primary: '#d39a38',
    secondary: '#c7835f',
    tertiary: '#2fc7c9',
  },
  {
    id: 'zib-follow-through',
    group: 'Field',
    name: 'Follow-Through',
    role: 'Touchpoint Operator',
    note: 'Runs outreach, check-ins, referrals, personal relationship upkeep, and post-delivery follow-up.',
    imageSrc: null,
    primary: '#2fc7c9',
    secondary: '#d39a38',
    tertiary: '#c95c6b',
  },
  {
    id: 'zib-sales-studio',
    group: 'Creative',
    name: 'Sales Studio',
    role: 'Proposal And Content Lead',
    note: 'Builds proposals, case studies, sales decks, content briefs, and presentation assets tied to revenue motion.',
    imageSrc: null,
    primary: '#d85f9d',
    secondary: '#d578b2',
    tertiary: '#2fc7c9',
  },
  {
    id: 'zib-brand-operator',
    group: 'Creative',
    name: 'Brand Operator',
    role: 'Publishing Rhythm',
    note: 'Keeps social, email, portfolio, and offer pages aligned with the owner’s current commercial priorities.',
    imageSrc: null,
    primary: '#d578b2',
    secondary: '#2fc7c9',
    tertiary: '#d39a38',
  },
  {
    id: 'zib-finance-admin',
    group: 'Systems',
    name: 'Finance Admin',
    role: 'Cash And Billing',
    note: 'Monitors invoices, subscriptions, cash timing, taxes, margin, and monthly close work.',
    imageSrc: null,
    primary: '#2fc7c9',
    secondary: '#738bd5',
    tertiary: '#67b26f',
  },
  {
    id: 'zib-systems-admin',
    group: 'Systems',
    name: 'Systems Admin',
    role: 'Tooling And Inbox',
    note: 'Keeps inboxes, CRM, calendars, automations, docs, and operational tooling clean enough to trust.',
    imageSrc: null,
    primary: '#738bd5',
    secondary: '#2fc7c9',
    tertiary: '#67b26f',
  },
  {
    id: 'zib-risk-review',
    group: 'Oversight',
    name: 'Risk Review',
    role: 'Promise And Cash Watch',
    note: 'Flags missed commitments, aging invoices, weak handoffs, stale leads, and relationships that need repair.',
    imageSrc: null,
    primary: '#c95c6b',
    secondary: '#d39a38',
    tertiary: '#2fc7c9',
  },
  {
    id: 'zib-quality-control',
    group: 'Oversight',
    name: 'Quality Control',
    role: 'Delivery Review',
    note: 'Checks client-ready work, recurring mistakes, owner bottlenecks, and what should be systematized next.',
    imageSrc: null,
    primary: '#d39a38',
    secondary: '#c95c6b',
    tertiary: '#2fc7c9',
  },
]

export const ZIB_PLACEHOLDERS = SCAVENJER_XYLOS_PROFILES
