import pg from 'pg'

const { Pool } = pg

let pool: pg.Pool | null = null

const getDatabaseUrl = () =>
  process.env.SUPABASE_DATABASE_URL?.trim() ||
  process.env.DATABASE_URL?.trim() ||
  null

export const hasSupabaseDatabaseConfig = () => Boolean(getDatabaseUrl())

export const getSupabaseDatabasePool = () => {
  const connectionString = getDatabaseUrl()
  if (!connectionString) {
    throw new Error('SUPABASE_DATABASE_URL is not configured.')
  }

  pool ??= new Pool({
    connectionString,
    ssl: {
      rejectUnauthorized: false,
    },
    max: 3,
  })

  return pool
}

export const closeSupabaseDatabasePool = async () => {
  const currentPool = pool
  pool = null
  await currentPool?.end()
}

export const writeSupabaseConnectionCheck = async (
  metadata: Record<string, unknown> = {},
) => {
  const client = await getSupabaseDatabasePool().connect()

  try {
    await client.query(`
      create table if not exists public.cortex_connection_checks (
        id bigint generated by default as identity primary key,
        checked_at timestamptz not null default now(),
        source text not null,
        metadata jsonb not null default '{}'::jsonb
      )
    `)

    const result = await client.query<{
      id: string
      checked_at: string
      source: string
    }>(
      `
        insert into public.cortex_connection_checks (source, metadata)
        values ($1, $2::jsonb)
        returning id::text, checked_at::text, source
      `,
      ['the-cortex', JSON.stringify(metadata)],
    )

    return result.rows[0]
  } finally {
    client.release()
  }
}
